---
# tasks file for roles/deploy_snmp
- name: mise à jour des paquets et installation des dernières MàJ
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes

- name: installation des paquets SNMP
  ansible.builtin.apt:
    pkg: 
      - snmp
      - snmpd
    state: latest      

- name: modification d'agentaddress
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regex: 'agentaddress 127\.0\.0\.1,\[::1\]'
    line: 'agentaddress udp:161'

- name: modification community 'public' par 'homelab'
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regex: '^rocommunity\s+public.*'
    line: 'rocommunity homelab'
    state: present

- name: modification community6 'public' par 'homelab'
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regex: '^rocommunity6\s+public.*'
    line: 'rocommunity6 homelab'
    state: present

- name: Redémarrage du service SNMP
  ansible.builtin.service:
    name: snmpd
    state: restarted